grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 1
model_selection:
  module_1:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
    search_param_grid:
      min_samples_leaf:
        - 4
      



