grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 40
      min_samples_leaf: 3
      max_depth: 6
    search_param_grid:
      min_samples_leaf:
       - 4
       - 6
      n_estimators:
       - 50
       - 80
      max_depth:
        - 4
        - 6
  module_1:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
      min_samples_split: 4
      max_depth: 2
    search_param_grid:
      min_samples_split:
        - 2
        - 3
      min_samples_leaf:
        - 2
        - 3
      max_depth:
        - 3
        - 4
  module_3:
    class: DecisionTreeRegressor
    module: sklearn.tree
    params:
      min_samples_split: 3
      min_samples_leaf: 4 
      max_depth : 2
      splitter: best
      max_features: auto 
    search_param_grid:
      min_samples_split:
        - 2
        - 4
      min_samples_leaf:
        - 2
        - 3
      max_depth:
        - 4
        - 3
      max_features: 
        - sqrt
        - log2



