grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_1:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
      min_samples_split: 4
      max_depth: 2
    search_param_grid:
      min_samples_split:
        - 2
        - 3
      min_samples_leaf:
        - 2
        - 3
      max_depth:
        - 3
        - 4




